import Head from 'next/head';

import NavBar from '../components/NavBar';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <NavBar />
      <div className={styles.container}>
        <Head>
          <title>Carbon emissions</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Carbon emissions</h1>

          <h2 className={styles.description}>
            Coming soon: Direct, frontline support for environmental and climate
            justice
          </h2>
        </main>
      </div>
    </>
  );
}
