import Head from 'next/head';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Carbon emissions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Carbon emissions</h1>

        <p className={styles.description}>
          Coming soon: Frontline support for environmental and climate justice
        </p>
      </main>
    </div>
  );
}
